react-ui:
  image:
    repository: core-sandbox-react-ui_1.1.0-feature-mo-ARCH-228-alt-SNAPSHOT_740d96bd
    tag: latest
  service:
    port: 3000

nodeapi:
  image:
    repository: core-sandbox-node-facade_1.1.0-feature-mo-ARCH-228-alt-SNAPSHOT_740d96bd
    tag: latest
  service:
    port: 3000

javaapi:
  image:
    repository: core-sandbox-java-service_1.1.0-feature-mo-ARCH-228-alt-SNAPSHOT_740d96bd
    tag: latest
  service:
    port: 8080
  env:
    SPRING_PROFILE: dev
