javaapi:
  image:
    repository: your-registry/javaapi
    tag: latest
  service:
    port: 8080

react-ui:
  image:
    repository: your-registry/react-ui
    tag: latest
  service:
    port: 3000

nodeapi:
  image:
    repository: your-registry/nodeapi
    tag: latest
  service:
    port: 3000

ingress:
  enabled: true
  host: myapp.example.com
  paths:
    - path: /api
      serviceName: javaapi
      servicePort: 8080
    - path: /ui
      serviceName: react-ui
      servicePort: 3000
    - path: /node
      serviceName: nodeapi
      servicePort: 3000
