apiVersion: v1
kind: Service
metadata:
  name: javaapi
spec:
  selector:
    app: javaapi
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
