apiVersion: apps/v1
kind: Deployment
metadata:
  name: { include "nodeapi.fullname" . }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: { include "nodeapi.name" . }
  template:
    metadata:
      labels:
        app: { include "nodeapi.name" . }
    spec:
      containers:
        - name: nodeapi
          image: "{ .Values.image.repository }:{ .Values.image.tag }"
          ports:
            - containerPort: { .Values.service.port }
