apiVersion: v1
kind: Service
metadata:
  name: nodeapi
spec:
  selector:
    app: nodeapi
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
