apiVersion: v1
kind: Service
metadata:
  name: { include "nodeapi.fullname" . }
spec:
  selector:
    app: { include "nodeapi.name" . }
  ports:
    - protocol: TCP
      port: { .Values.service.port }
      targetPort: { .Values.service.port }
