apiVersion: v1
kind: Service
metadata:
  name: react-ui
spec:
  selector:
    app: react-ui
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
