apiVersion: v1
kind: Service
metadata:
  name: { include "react-ui.fullname" . }
spec:
  selector:
    app: { include "react-ui.name" . }
  ports:
    - protocol: TCP
      port: { .Values.service.port }
      targetPort: { .Values.service.port }
